name: Discord Notification

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord notification
      run: |
        MESSAGE="New commit: ${{ github.event.head_commit.message }}"
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content": "'"$MESSAGE"'"}' \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
